# Generated by Django 6.0.6 on 2026-06-21 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст объявления')),
                ('published_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
            ],
            options={
                'verbose_name': 'объявление',
                'verbose_name_plural': 'объявления',
                'ordering': ['-published_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('electricity', 'Электричество'), ('water', 'Вода'), ('gas', 'Газ'), ('other', 'Другое')], default='electricity', max_length=30, verbose_name='тип')),
                ('number', models.CharField(max_length=100, verbose_name='номер счетчика')),
                ('unit', models.CharField(default='кВт*ч', max_length=30, verbose_name='единица измерения')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
            ],
            options={
                'verbose_name': 'счетчик',
                'verbose_name_plural': 'счетчики',
                'ordering': ['plot__number', 'kind', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30, unique=True, verbose_name='номер участка')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='площадь, соток')),
                ('owner_name', models.CharField(blank=True, max_length=255, verbose_name='владелец')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='адрес/ориентир')),
                ('note', models.TextField(blank=True, verbose_name='примечание')),
            ],
            options={
                'verbose_name': 'участок',
                'verbose_name_plural': 'участки',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='текущее показание')),
                ('photo', models.FileField(blank=True, upload_to='meter_readings/', verbose_name='фото счетчика')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='передано')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='статус')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий администратора')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.meter', verbose_name='счетчик')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_readings', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'показание счетчика',
                'verbose_name_plural': 'показания счетчиков',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма оплаты')),
                ('paid_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата оплаты')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('bank', 'Банк'), ('other', 'Другое')], default='bank', max_length=20, verbose_name='способ оплаты')),
                ('photo', models.FileField(blank=True, upload_to='payment_receipts/', verbose_name='фото квитанции')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='загружено')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.plot', verbose_name='участок')),
            ],
            options={
                'verbose_name': 'квитанция оплаты',
                'verbose_name_plural': 'квитанции оплат',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('paid_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата оплаты')),
                ('method', models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('bank', 'Банк'), ('other', 'Другое')], default='bank', max_length=20, verbose_name='способ оплаты')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('confirmed', 'Подтверждено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='статус')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.plot', verbose_name='участок')),
            ],
            options={
                'verbose_name': 'оплата',
                'verbose_name_plural': 'оплаты',
                'ordering': ['-paid_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='meter',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='core.plot', verbose_name='участок'),
        ),
        migrations.CreateModel(
            name='Accrual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='назначение')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сумма')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='период')),
                ('charged_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='дата начисления')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('canceled', 'Отменено')], default='active', max_length=20, verbose_name='статус')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='core.plot', verbose_name='участок')),
            ],
            options={
                'verbose_name': 'начисление',
                'verbose_name_plural': 'начисления',
                'ordering': ['-charged_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PlotMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Владелец'), ('family', 'Член семьи'), ('manager', 'Представитель')], default='owner', max_length=20, verbose_name='роль')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='добавлен')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.plot', verbose_name='участок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_memberships', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'связь пользователя с участком',
                'verbose_name_plural': 'связи пользователей с участками',
                'unique_together': {('user', 'plot')},
            },
        ),
    ]
