# Generated by Django 6.0.6 on 2026-06-21 11:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accrual',
            options={'ordering': ['-charged_at', '-id'], 'verbose_name': 'нарахування', 'verbose_name_plural': 'нарахування'},
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-published_at', '-id'], 'verbose_name': 'оголошення або новина', 'verbose_name_plural': 'оголошення та новини'},
        ),
        migrations.AlterModelOptions(
            name='meter',
            options={'ordering': ['plot__number', 'kind', 'number'], 'verbose_name': 'лічильник', 'verbose_name_plural': 'лічильники'},
        ),
        migrations.AlterModelOptions(
            name='meterreading',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'показання лічильника', 'verbose_name_plural': 'показання лічильників'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at', '-id'], 'verbose_name': 'оплата', 'verbose_name_plural': 'оплати'},
        ),
        migrations.AlterModelOptions(
            name='paymentreceipt',
            options={'ordering': ['-created_at'], 'verbose_name': 'квитанція оплати', 'verbose_name_plural': 'квитанції оплат'},
        ),
        migrations.AlterModelOptions(
            name='plot',
            options={'ordering': ['number'], 'verbose_name': 'ділянка', 'verbose_name_plural': 'ділянки'},
        ),
        migrations.AlterModelOptions(
            name='plotmembership',
            options={'verbose_name': 'звʼязок користувача з ділянкою', 'verbose_name_plural': 'звʼязки користувачів з ділянками'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='kind',
            field=models.CharField(choices=[('critical', 'Важливе оголошення'), ('announcement', 'Оголошення'), ('news', 'Новина селища')], default='announcement', max_length=30, verbose_name='тип'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='topic',
            field=models.CharField(choices=[('infrastructure', 'Інфраструктура'), ('shops', 'Магазини'), ('post', 'Пошта'), ('roads', 'Дороги'), ('water', 'Вода'), ('electricity', 'Електрика'), ('events', 'Події селища'), ('general', 'Загальні повідомлення')], default='general', max_length=30, verbose_name='тема новини'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сума'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='charged_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='дата нарахування'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='comment',
            field=models.TextField(blank=True, verbose_name='коментар'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='створено'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='period',
            field=models.CharField(blank=True, max_length=100, verbose_name='період'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accruals', to='core.plot', verbose_name='ділянка'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='status',
            field=models.CharField(choices=[('active', 'Активне'), ('canceled', 'Скасоване')], default='active', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='accrual',
            name='title',
            field=models.CharField(max_length=255, verbose_name='призначення'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='створено'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубліковано'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='дата публікації'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='text',
            field=models.TextField(verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активний'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='kind',
            field=models.CharField(choices=[('electricity', 'Електрика'), ('water', 'Вода'), ('gas', 'Газ'), ('other', 'Інше')], default='electricity', max_length=30, verbose_name='тип'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='number',
            field=models.CharField(max_length=100, verbose_name='номер лічильника'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='core.plot', verbose_name='ділянка'),
        ),
        migrations.AlterField(
            model_name='meter',
            name='unit',
            field=models.CharField(default='кВт*год', max_length=30, verbose_name='одиниця вимірювання'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='comment',
            field=models.TextField(blank=True, verbose_name='коментар адміністратора'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='meter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='core.meter', verbose_name='лічильник'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='photo',
            field=models.FileField(blank=True, upload_to='meter_readings/', verbose_name='фото лічильника'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='status',
            field=models.CharField(choices=[('pending', 'На перевірці'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meter_readings', to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='поточне показання'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сума'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='коментар'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='створено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Готівка'), ('card', 'Картка'), ('bank', 'Банк'), ('other', 'Інше')], default='bank', max_length=20, verbose_name='спосіб оплати'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='дата оплати'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.plot', verbose_name='ділянка'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'На перевірці'), ('confirmed', 'Підтверджено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сума оплати'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='comment',
            field=models.TextField(blank=True, verbose_name='коментар'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='завантажено'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='method',
            field=models.CharField(choices=[('cash', 'Готівка'), ('card', 'Картка'), ('bank', 'Банк'), ('other', 'Інше')], default='bank', max_length=20, verbose_name='спосіб оплати'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='paid_at',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='дата оплати'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='photo',
            field=models.FileField(blank=True, upload_to='payment_receipts/', verbose_name='фото квитанції'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.plot', verbose_name='ділянка'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='status',
            field=models.CharField(choices=[('pending', 'На перевірці'), ('confirmed', 'Підтверджено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='адреса або орієнтир'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='площа, соток'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='note',
            field=models.TextField(blank=True, verbose_name='примітка'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='number',
            field=models.CharField(max_length=30, unique=True, verbose_name='номер ділянки'),
        ),
        migrations.AlterField(
            model_name='plot',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='власник'),
        ),
        migrations.AlterField(
            model_name='plotmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='додано'),
        ),
        migrations.AlterField(
            model_name='plotmembership',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.plot', verbose_name='ділянка'),
        ),
        migrations.AlterField(
            model_name='plotmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Власник'), ('family', 'Член родини'), ('manager', 'Представник')], default='owner', max_length=20, verbose_name='роль'),
        ),
        migrations.AlterField(
            model_name='plotmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_memberships', to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='телефон')),
                ('avatar', models.FileField(blank=True, upload_to='avatars/', verbose_name='аватар')),
                ('access_status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='статус доступу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='користувач')),
            ],
            options={
                'verbose_name': 'профіль користувача',
                'verbose_name_plural': 'профілі користувачів',
            },
        ),
    ]
