# Generated by Django 6.0.6 on 2026-06-21 12:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_accrual_options_alter_announcement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plotmembership',
            options={'verbose_name': 'привʼязка користувача до ділянки', 'verbose_name_plural': 'привʼязки користувачів до ділянок'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'профіль користувача', 'verbose_name_plural': 'профілі користувачів'},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='access_status',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', max_length=100, verbose_name='імʼя'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='прізвище'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='по батькові'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(db_index=True, max_length=30, verbose_name='номер телефону'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
        ),
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=30, verbose_name='номер телефону')),
                ('code_hash', models.CharField(max_length=255, verbose_name='хеш коду')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='створено')),
                ('expires_at', models.DateTimeField(verbose_name='діє до')),
                ('used', models.BooleanField(default=False, verbose_name='використано')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='час використання')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='кількість спроб')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_codes', to=settings.AUTH_USER_MODEL, verbose_name='користувач')),
            ],
            options={
                'verbose_name': 'одноразовий код входу',
                'verbose_name_plural': 'одноразові коди входу',
                'ordering': ['-created_at'],
            },
        ),
    ]
