# Generated by Django 6.0.6 on 2026-06-28 15:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_plotmembership_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='photo',
            field=models.FileField(blank=True, upload_to='meter_readings/', validators=[core.models.validate_meter_photo], verbose_name='фото лічильника'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='photo',
            field=models.FileField(blank=True, upload_to='payment_receipts/', validators=[core.models.validate_payment_receipt_file], verbose_name='фото квитанції'),
        ),
    ]
