# Generated by Django 6.0.6 on 2026-06-29 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_meterreading_photo_alter_paymentreceipt_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Готівка'), ('card', 'Картка'), ('bank', 'Банк'), ('online', 'Онлайн'), ('other', 'Інше')], default='bank', max_length=20, verbose_name='спосіб оплати'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='method',
            field=models.CharField(choices=[('cash', 'Готівка'), ('card', 'Картка'), ('bank', 'Банк'), ('online', 'Онлайн'), ('other', 'Інше')], default='bank', max_length=20, verbose_name='спосіб оплати'),
        ),
        migrations.CreateModel(
            name='OnlinePaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='сума')),
                ('provider', models.CharField(choices=[('liqpay', 'LiqPay'), ('wayforpay', 'WayForPay')], default='liqpay', max_length=20, verbose_name='провайдер')),
                ('order_id', models.CharField(max_length=80, unique=True, verbose_name='внутрішній номер замовлення')),
                ('provider_payment_id', models.CharField(blank=True, max_length=120, verbose_name='ID платежу провайдера')),
                ('status', models.CharField(choices=[('created', 'Створено'), ('pending', 'Очікує оплати'), ('success', 'Успішно оплачено'), ('failed', 'Неуспішна оплата'), ('canceled', 'Скасовано')], default='created', max_length=20, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='дата успішної оплати')),
                ('provider_status', models.CharField(blank=True, max_length=80, verbose_name='статус провайдера')),
                ('provider_payload', models.JSONField(blank=True, default=dict, verbose_name='дані провайдера')),
                ('accrual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payment_transactions', to='core.accrual', verbose_name='нарахування')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='online_transaction', to='core.payment', verbose_name='створена оплата')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payment_transactions', to='core.plot', verbose_name='ділянка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='користувач')),
            ],
            options={
                'verbose_name': 'онлайн-транзакція',
                'verbose_name_plural': 'онлайн-транзакції',
                'ordering': ['-created_at'],
            },
        ),
    ]
